# Generated by Django 4.2.3 on 2023-07-18 22:00

import apps.events.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[apps.events.models.event_id_check])),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('max_capacity', models.IntegerField()),
                ('passed_generated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventPass',
            fields=[
                ('pass_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('qr', models.URLField(unique=True, validators=[django.core.validators.URLValidator])),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
