# Generated by Django 4.2 on 2023-07-28 07:40

import apps.events.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, validators=[apps.events.models.event_id_check])),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=256)),
                ('max_capacity', models.IntegerField()),
                ('passes_generated', models.IntegerField()),
                ('image', models.URLField(default='https://www.freeiconspng.com/thumbs/no-image-icon/no-image-icon-6.png')),
                ('calendar_url', models.URLField(default='#')),
                ('is_booking', models.BooleanField(default=False)),
                ('is_display', models.BooleanField(default=False)),
                ('slots_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('slot_id', models.CharField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=256)),
                ('calendar_url', models.URLField(default='#')),
                ('passes_generated', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPass',
            fields=[
                ('pass_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('qr', models.URLField(unique=True, validators=[django.core.validators.URLValidator])),
                ('entry_status', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
