# Generated by Django 4.2.3 on 2023-07-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='passed_generated',
            new_name='passes_generated',
        ),
    ]
