# Generated by Django 4.2 on 2023-07-28 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 7, 56, 6, 823696, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventslot',
            name='max_capacity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventslot',
            name='venue',
            field=models.CharField(default='Main Auditorium', max_length=256),
            preserve_default=False,
        ),
    ]
