# Generated by Django 4.2.3 on 2023-07-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_passed_generated_event_passes_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(default='https://www.freeiconspng.com/thumbs/no-image-icon/no-image-icon-6.png'),
        ),
        migrations.AddField(
            model_name='eventpass',
            name='entry_status',
            field=models.BooleanField(default=False),
        ),
    ]
