# Generated by Django 4.2 on 2023-07-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventslot_date_eventslot_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslot',
            name='slot_id',
            field=models.CharField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
