# Generated by Django 4.2.3 on 2023-07-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image_eventpass_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_url',
            field=models.URLField(default='#'),
        ),
    ]
