# Generated by Django 4.2 on 2023-07-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventslot_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpass',
            name='slot_id',
            field=models.ForeignKey(default='efkwkfjfw', on_delete=django.db.models.deletion.RESTRICT, to='events.eventslot'),
            preserve_default=False,
        ),
    ]
