# Generated by Django 4.2 on 2023-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventpass_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slot_id',
            field=models.CharField(default='lmao', max_length=16),
        ),
    ]
