# Generated by Django 4.2 on 2023-07-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_slot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpass',
            name='slot_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.eventslot'),
        ),
    ]
