# Generated by Django 4.2 on 2023-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventpass_slot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_required',
            field=models.BooleanField(default=True),
        ),
    ]
