# Generated by Django 4.2 on 2023-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_booking_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpass',
            name='time',
            field=models.CharField(default='edwedwe', max_length=256),
            preserve_default=False,
        ),
    ]
