# Generated by Django 4.2.2 on 2023-07-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
