# Generated by Django 4.2 on 2023-07-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.URLField(default='345235524'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='qr',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='secure_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
