# Generated by Django 4.2 on 2023-08-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_gender_user_image_user_qr_user_secure_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qr',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secure_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
