# Generated by Django 4.2.3 on 2023-07-24 00:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), default=['None'], max_length=50, size=None),
        ),
    ]
