# Generated by Django 4.2 on 2023-08-11 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0001_initial'),
        ('users', '0003_alter_user_qr_alter_user_secure_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hoods.hood'),
        ),
    ]
