# Generated by Django 4.2 on 2023-08-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0004_delete_hoodpreference'),
        ('users', '0005_alter_user_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hoods.hood'),
        ),
    ]
