# Generated by Django 4.2.3 on 2023-07-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
    ]
