# Generated by Django 4.2.3 on 2023-07-24 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, max_length=50, size=None),
        ),
    ]
