# Generated by Django 4.2 on 2023-08-11 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hoods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hood_1', to='hoods.hood')),
                ('hood_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hood_2', to='hoods.hood')),
                ('hood_3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hood_3', to='hoods.hood')),
                ('hood_4', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hood_4', to='hoods.hood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
