# Generated by Django 4.2 on 2023-08-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0003_hoodpreference_datetime_alter_hood_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HoodPreference',
        ),
    ]
