# Generated by Django 4.2 on 2023-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0004_delete_hoodpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
